### ISSUE TITLE
Difference between Combo(Focal+Dice) and FocalLosswithDice

### ISSUE THREAD

**Issue by hihunjin** [selimsef/xview2_solution#10]
You used both Combo([Focal+Dice](https://github.com/selimsef/xview2_solution/blob/ab7f7a69154b43cd195201d9773aa295c3b89452/configs/d161.json#L28)) and [FocalLossWithDice](https://github.com/selimsef/xview2_solution/blob/ab7f7a69154b43cd195201d9773aa295c3b89452/configs/se50_softmax.json#L28).

I wonder why you used them both. Are they different? It seems you used ComboLoss on Localization network and FocalLossWithDice on Prediction network.

**Comment by selimsef** [comment]
Combo is used for binary crossentropy and binary masks, FocalLosswithDice is used for multiclass masks
